feature: first version of light mode for app
arguflow/app pull request #75
Opened 2023-03-14 06:24 UTC by amaransen

Nostr ID connection page:
![image](https://user-images.githubusercontent.com/77699109/224913304-7bb35ae7-5c6f-4e85-83ef-3d2a267dc9c0.png)

Topics page:
![image](https://user-images.githubusercontent.com/77699109/224913081-c067b1d6-346c-454e-afbe-6127a09f4407.png)

Value split + Value entry:
![image](https://user-images.githubusercontent.com/77699109/224913669-14806458-7bcc-4a3c-9bf5-072f480b9b4c.png)

Initial Statements (Warrant unexpanded):

2023-03-16 18:33 UTC, fastfists commented
Look really good only thing is that I think we should standardize how the profile picture view looks
![image](https://user-images.githubusercontent.com/32852291/225719523-88f18160-6d24-477e-8e47-bde0730de1b9.png)

aside from that looks good to me

2023-03-23 03:51 UTC, kmkhami requested changes
Please add the prettier and eslint extensions to your VSCode. 

I'd like to fix the linting errors and check if there are any other ones before merging this. 

I'd also like to make sure we ship the controller button in the navbar before merging this. 

In summary: 

- [ ] prettier and eslint checks
- [ ] controller button in the navbar

2023-03-23 03:51 UTC, kmkhami commented on src/components/Atoms/Combobox.tsx
> +          <Menu class="flex w-full rounded flex-col space-y-1 overflow-y-auto bg-pink-50 dark:bg-gray-800 shadow-lg ring-1 ring-black ring-opacity-5 overflow-x-hidden">
```suggestion
          <Menu class="flex w-full flex-col space-y-1 overflow-y-auto rounded bg-pink-50 shadow-lg ring-1 ring-black ring-opacity-5 overflow-x-hidden dark:bg-gray-800">
```

Linter wants a different class order

2023-03-23 03:51 UTC, kmkhami commented on src/components/Atoms/InputRowsForm.tsx
> +    <div class={`w-full rounded border dark:${borderColor()} px-2 py-2 border-fuchsia-400 dark:text-white `}
```suggestion
    <div
      class={`w-full rounded border dark:${borderColor()} border-fuchsia-400 px-2 py-2 dark:text-white `}
    >
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Atoms/InputRowsForm.tsx
> +                    class="w-full rounded border border-fuchsia-300 dark:border-white dark:bg-slate-900 px-2 dark:text-white"
```suggestion
                    class="w-full rounded border border-fuchsia-300 px-2 dark:border-white dark:bg-slate-900 dark:text-white"
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Atoms/InputRowsForm.tsx
> +                    class="w-full rounded border border-fuchsia-300 dark:border-white dark:bg-slate-900 px-2 text-black dark:text-white"
```suggestion
                    class="w-full rounded border border-fuchsia-300 px-2 text-black dark:border-white dark:bg-slate-900 dark:text-white"
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/CounterArgument/CounterArgumentView.tsx
> +        "flex flex-col space-y-2 rounded-md border-2 p-2 text-black dark:text-white": true,
```suggestion
       "flex flex-col space-y-2 rounded-md border-2 p-2 text-black dark:text-white":
          true,
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Statements/AddStatementButton.tsx
> +            class="flex w-fit cursor-pointer items-center space-x-2 rounded-lg border-2 border-blue-500 dark:border-white px-4 py-3 text-blue-600 dark:text-white"
```suggestion
            class="flex w-fit cursor-pointer items-center space-x-2 rounded-lg border-2 border-blue-500 px-4 py-3 text-blue-600 dark:border-white dark:text-white"
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Topics/TopicsDisplay.tsx
> +            class="rounded-full border border-teal-300 dark:border-green-700 bg-transparent p-2 text-green-500"
```suggestion
            class="rounded-full border border-teal-300 bg-transparent p-2 text-green-500 dark:border-green-700"
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Topics/TopicsDisplay.tsx
> +        <div class="w-fit text-2xl font-bold text-blue-700 dark:text-white">Your Topics</div>
```suggestion
        <div class="w-fit text-2xl font-bold text-blue-700 dark:text-white">
          Your Topics
        </div>
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Topics/TopicsDisplay.tsx
> +      <div class="flex w-full items-center justify-center space-x-3 border-b border-violet-400 dark:border-slate-700 py-2">
```suggestion
        <div class="flex w-full flex-col items-center justify-center space-y-6 rounded-lg border border-violet-400 py-2 dark:border-slate-600 md:max-w-[75%]">
      <div class="flex w-full items-center justify-center space-x-3 border-b border-violet-400 py-2 dark:border-slate-700">
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Topics/TopicsList.tsx
> +                <div class="p-4 text-lg font-bold text-blue-600 dark:text-white border rounded-lg border-violet-400">
```suggestion
                <div class="rounded-lg border border-violet-400 p-4 text-lg font-bold text-blue-600 dark:text-white">
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/Topics/ValueSplitButton.tsx
> +                  <Menu class="left-0 mt-1 flex w-full origin-top-left flex-col space-y-1 rounded-lg bg-fuchsia-200 dark:bg-gray-800 p-1 py-2 shadow-lg ring-1 ring-black ring-opacity-5">
```suggestion
                  <Menu class="left-0 mt-1 flex w-full origin-top-left flex-col space-y-1 rounded-lg bg-fuchsia-200 p-1 py-2 shadow-lg ring-1 ring-black ring-opacity-5 dark:bg-gray-800">
```

2023-03-23 03:51 UTC, kmkhami commented on src/components/layouts/ApplicationLayout.tsx
> +    <div class="min-h-screen w-screen bg-pink-50 dark:bg-black overflow-x-hidden">
```suggestion
    <div class="min-h-screen w-screen bg-pink-50 overflow-x-hidden dark:bg-black">
```

2023-03-23 03:51 UTC, kmkhami commented on src/routes/topics/[id].tsx
> +          <div class="flex w-full flex-col items-center justify-center space-y-6 rounded-lg border border-emerald-300 dark:border-slate-600 p-2 md:px-8 md:py-4">
```suggestion
          <div class="flex w-full flex-col items-center justify-center space-y-6 rounded-lg border border-emerald-300 p-2 dark:border-slate-600 md:px-8 md:py-4">
```

2023-03-23 03:51 UTC, kmkhami commented on src/root.tsx
> +    setDark = "dark";
```suggestion
  let setDark = "";
  if (
    localStorage.theme === "dark" ||
    (!("theme" in localStorage) &&
      window.matchMedia("(prefers-color-scheme: dark)").matches)
  )
    setDark = "dark";
```

2023-04-07 06:09 UTC, merged